main.pdf: main.tex preamble.tex bfsdfs.tex  bloom.tex  dijkstra.tex  javacollections.tex  linkedlists.tex  recursion.tex
	/opt/local/bin/latexmk -gg

.PHONY: clean
clean:
	rm -f *.aux *.bbl *.bcf *.blg *.fdb_latexmk *.lof *.log *.lot *.fls *.out *.toc main.pdf
